# This file was generated by GoReleaser. DO NOT EDIT.
cask "orion" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/orion"]
    end
  end

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "eee523d3490b4bb611cc660d1d1348d75138fe73ef66ff5d4d20b7318a89efcc"
      url "https://github.com/olliejudge/orion/releases/download/v#{version}/orion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "49612f718008b729d93e77f85f7c1b51b26cfde51135ae1333545d89887de273"
      url "https://github.com/olliejudge/orion/releases/download/v#{version}/orion_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5bb8bd16857f71ffd012f5b489e756475c3e302753210f1661a2dda3429e160d"
      url "https://github.com/olliejudge/orion/releases/download/v#{version}/orion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd438810f4c51a1e790fa2fabfce7d7de753a5fb709edeb0f1960092fccefbc8"
      url "https://github.com/olliejudge/orion/releases/download/v#{version}/orion_#{version}_linux_amd64.tar.gz"
    end
  end

  name "orion"
  desc "Live, animated map of a git repository across all its worktrees"
  homepage "https://github.com/olliejudge/orion"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "orion"

  # No zap stanza required

  caveats <<~EOS
    Run `orion` inside any git repository. It serves on 127.0.0.1 only.
  EOS
end
